site_name: OSLC Developer Guide
site_url: https://oslc.github.io/developing-oslc-applications/
site_description: Learn to develop OSLC applications
docs_dir: docs-new

repo_name: oslc/developing-oslc-applications
repo_url: https://github.com/oslc/developing-oslc-applications
edit_uri: edit/gh-pages/docs-new/

theme:
  name: material
  
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    - scheme: default
      # primary: indigo
      # accent: indigo
      # primary: 'blue grey'
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/logo-old-50px.png
  logo: img/oslc-logo-white-100.png

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oslc
    - icon: fontawesome/solid/globe
      link: https://open-services.net

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: oslc-op
      repo: developing-oslc-applications
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:  
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;'
  - redirects:
      redirect_maps:
        'eclipse_lyo/eclipse-lyo.html': 'eclipse_lyo/eclipse-lyo.md'
        'eclipse_lyo/setup-an-oslc-provider-consumer-application.html': 'eclipse_lyo/setup-an-oslc-provider-consumer-application.md'
        'eclipse_lyo/lyo-designer.html': 'eclipse_lyo/designer.md'
        'eclipse_lyo/lyo-core-internals.html': 'eclipse_lyo/lyo-core-internals.md'
        'eclipse_lyo/install-lyo-designer.html': 'eclipse_lyo/install-lyo-designer.md'
        'eclipse_lyo/eclipse-setup-for-lyo-based-development.html': 'eclipse_lyo/eclipse-setup-for-lyo-based-development.md'
        'eclipse_lyo/toolchain-modelling-workshop.html': 'eclipse_lyo/toolchain-modelling-workshop.md'
        'eclipse_lyo/domain-specification-modelling-workshop.html': 'eclipse_lyo/domain-specification-modelling-workshop.md'
        'eclipse_lyo/modelling-howto.html': 'eclipse_lyo/modelling-howto.md'
        'eclipse_lyo/lyo-as-osgi-bundles.html': 'eclipse_lyo/lyo-as-osgi-bundles.md'
        'tutorials.html': 'tutorials.md'
        'sample-applications-and-code.html': 'sample-applications-and-code.md'
        'technical-foundations.html': 'technical-foundations.md'
        'why-develop-oslc-applications.html': 'why-develop-oslc-applications.md'
        'services-resources-and-design-patterns.html': 'services-resources-and-design-patterns.md'
        'oslc-open-source-node-projects.html': 'oslc-open-source-node-projects.md'
        'iotp-adaptor-sample.html': 'iotp-adaptor-sample.md'
        'additional-security-considerations.html': 'additional-security-considerations.md'
        'iotp-adaptor-sample.html': 'iotp-adaptor-sample.html'
        'additional-security-considerations.html': 'additional-security-considerations.html'
        'iotp-adaptor-sample.html': 'iotp-adaptor-sample/'
        'additional-security-considerations.html': 'additional-security-considerations/'
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

nav:
  - OSLC for Developers: 
    - OSLC explainer: index.md
    - Why Develop OSLC Applications: why-develop-oslc-applications.md
    - Technical Foundations: technical-foundations.md
    - Tutorials: tutorials.md
    - Services & Design Patterns: services-resources-and-design-patterns.md
    - Security: additional-security-considerations.md
    - Integration Tutorial: 
      - Overview: integrating_products_with_oslc/index.md
      - OSLC Introduction: integrating_products_with_oslc/overview_of_oslc.md
      - Running Examples: integrating_products_with_oslc/running_the_examples.md
      - Implementing Provider:
        - Getting Started: integrating_products_with_oslc/implementing_an_oslc_provider/1_0_implementing_a_provider.md
        - Planning Provider: integrating_products_with_oslc/implementing_an_oslc_provider/1_1_planning_partial_cm_provider.md
        - Service Resources: integrating_products_with_oslc/implementing_an_oslc_provider/1_2_providing_service_resources.md
        - Intro to OSLC4J: integrating_products_with_oslc/implementing_an_oslc_provider/1_3_intro_to_oslc4j.md
        - UI Preview: integrating_products_with_oslc/implementing_an_oslc_provider/1_4_ui_preview.md
        - UI Selection: integrating_products_with_oslc/implementing_an_oslc_provider/1_5_ui_selection.md
        - UI Creation: integrating_products_with_oslc/implementing_an_oslc_provider/1_6_ui_creation.md
        - Factory: integrating_products_with_oslc/implementing_an_oslc_provider/1_7_factory.md
      - Implementing Consumer:
        - Getting Started: integrating_products_with_oslc/integrating_with_an_oslc_provider/2_0_implementing_consumer.md
        - Use Cases: integrating_products_with_oslc/integrating_with_an_oslc_provider/2_1_consumer_use_cases.md
        - Links & Previews: integrating_products_with_oslc/integrating_with_an_oslc_provider/2_2_links_and_previews.md
        - Delegated UI: integrating_products_with_oslc/integrating_with_an_oslc_provider/2_3_delegatedUI.md
        - Notify Customers: integrating_products_with_oslc/integrating_with_an_oslc_provider/2_4_notify_customers.md
        - Automatic Bugs: integrating_products_with_oslc/integrating_with_an_oslc_provider/2_5_automatic_bugs.md
  - Eclipse Lyo:    
    - Lyo Java SDK:
      - Overview: eclipse_lyo/eclipse-lyo.md
      - Setup Guide: eclipse_lyo/setup-an-oslc-provider-consumer-application.md
      - Eclipse Setup: eclipse_lyo/eclipse-setup-for-lyo-based-development.md
      - Migration Guides:
        - Migration Overview: eclipse_lyo/migration-overview.md
        - Lyo 2.x → 4.x: eclipse_lyo/migration-2x-4x.md
        - Lyo 4.x → 5.x: eclipse_lyo/migration-4x-5x.md
        - Lyo 5.x → 6.x: eclipse_lyo/migration-5x-6x.md
        - Lyo 6.x → 7.x: eclipse_lyo/migration-6x-7x.md
      - Advanced topics:
        - Core Internals: eclipse_lyo/lyo-core-internals.md
        - OSGi Bundles: eclipse_lyo/lyo-as-osgi-bundles.md
    - Lyo Designer:
      - Introduction: eclipse_lyo/designer.md
      - Installing Designer: eclipse_lyo/install-lyo-designer.md
      - Modelling How-To: eclipse_lyo/modelling-howto.md
      - Domain Specification workshop: eclipse_lyo/domain-specification-modelling-workshop.md
      - Toolchain Modelling workshop: eclipse_lyo/toolchain-modelling-workshop.md
  - OSLC4JS: oslc-open-source-node-projects.md
  - OSLC4Net: https://oslc4net.github.io/
  - PyOSLC: https://github.com/cslab/pyoslc
  - Sample Applications:
    - Overview: sample-applications-and-code.md
    - IoTP Adaptor: 
        - IoTP Adaptor Sample: iotp-adaptor-sample.md
        - User Guide: iotp_adaptor/userGuide/user-guide.md
        - Developer Guide: iotp_adaptor/developer-guide.md
        - Getting Started:
            - Environment Setup: iotp_adaptor/environment-setup.md
            - Exploring Generated Code: iotp_adaptor/exploring-the-code.md
            - Implementing Domain Classes: iotp_adaptor/implement-domain-class.md
            - JUnit Testing: iotp_adaptor/junit-tests.md
        - Modeling & Code Generation:
            - Toolchain Model: iotp_adaptor/toolchain-model.md
            - Code Generation: iotp_adaptor/code-generator.md
        - Jazz.net Integration:
            - Authentication: iotp_adaptor/authentication.md
            - SSL Support: iotp_adaptor/ssl-support.md
            - Root Services: iotp_adaptor/rootservices.md
            - Consumer/Friend Connections: iotp_adaptor/consumer-friend.md
            - Artifact Container Associations: iotp_adaptor/artifact-container-associations.md
            - Delegated Dialogs: iotp_adaptor/dialogs.md
            - TRS Provider: iotp_adaptor/trs-provider.md
