name: Harp CI

on:
  push:
    branches: [ gh-pages ]
#   pull_request:
#     branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      with:
         # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
         node-version: 'lts/*'
#         # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version
#         node-version-file: # optional
#         # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm
#         cache: # optional
#         # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
#         cache-dependency-path: # optional
 
    - name: Install Harp
      run: |
        npm i harp
    - name: Build
      run: |
        harp ./_harp/ .
    - name: Deploy
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add -A
        git commit -m "Harp rebuild"
        git push origin gh-pages
        
